With WebDriverManager
VictorKozhushko/Module2 pull request #8
Opened 2020-01-20 10:01 UTC by VictorKozhushko

Framework exercises with one defined mistake due to the change of package.

2020-01-20 10:03 UTC, VictorKozhushko commented
The name of Page from the old package was in new Test

2020-01-21 11:04 UTC, AndreiValnianka commented on src/test/java/com/epam/ta/test/GoogleCloudCalculatorTest.java
> +        driver.switchTo().window(tab10MinutEmail);
instead of this construction create method
 
public void switchOnFirstTab() {
driver.switchTo().window(tabs.get(0));
}

2020-01-21 11:04 UTC, AndreiValnianka commented on src/test/java/com/epam/ta/test/GoogleCloudCalculatorTest.java
> +        computingEnginePage.estimateViaEmail(email);
computingEnginePage.estimateViaEmail(tenMinutEmailPage.getEmailAddress());

email is an unnecessary variable

2020-01-21 11:05 UTC, AndreiValnianka commented on src/test/java/com/epam/ta/test/GoogleCloudCalculatorTest.java
> +    }
Very big method. Please divide.

2020-01-21 11:05 UTC, AndreiValnianka commented on src/test/java/test/WebDriverGoogleCloudCalculatorTest.java
> +//    }
What is this?

2020-01-21 11:12 UTC, AndreiValnianka requested changes
1. Pages should contain locators(private) and simple methods for dealing with these locators (public). So move logic from page layer to test or service layer.
2. Divide big methods (very hard to understand them). 
3. Can't find these tasks
![ice_screenshot_20200121-141059](https://user-images.githubusercontent.com/37652976/72800275-fea0e500-3c57-11ea-95c1-74e3e7a9ea31.png)

2020-01-28 13:49 UTC, AndreiValnianka commented on src/test/java/com/epam/ta/test/CommonConditions.java
>      public static void stopBrowser() {
This method does nothing

2020-01-28 13:53 UTC, AndreiValnianka commented on src/test/java/com/epam/ta/page/google/GoogleComputingEnginePage.java
> +        }
Pages should contain locators and methods which perform actions with locators. Move logic to test or service layer

2020-01-28 13:53 UTC, AndreiValnianka approved these changes
See comments

2020-01-28 13:53 UTC, merged